name: Scraping Diario Grupo 5

on:
  schedule:
    - cron: '0 3 * * *'  # 3 AM UTC = 10 PM hora Perú
  workflow_dispatch:

permissions:
  contents: write  # Permitir que el bot de GitHub Actions haga push

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3
      
    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: pip install requests beautifulsoup4

    - name: Ejecutar scraper.py
      run: python scraper.py

    - name: Push cambios
      env:
        TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/Brayan456/Scrapping-G5.git
        git add .
        git commit -m "Scraping automático: $(date +'%Y-%m-%d')" || echo "No hay cambios"
        git push origin HEAD:${{ github.ref_name }}
