name: Scraping Diario Grupo 5

on:
  schedule:
    - cron: '0 3 * * *'  # 3 AM UTC = 10 PM Perú
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install requests beautifulsoup4 dropbox pandas

      - name: Ejecutar scraper.py
        run: python scraper.py

      - name: Subir archivos a Dropbox (con refresh token automático)
        env:
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
        run: |
          python <<EOF
          import os
          import requests
          import dropbox
          from datetime import datetime

          print("[*] Renovando access_token de Dropbox...")
          res = requests.post(
              "https://api.dropboxapi.com/oauth2/token",
              data={
                  "grant_type": "refresh_token",
                  "refresh_token": os.environ["DROPBOX_REFRESH_TOKEN"]
              },
              auth=(os.environ["DROPBOX_APP_KEY"], os.environ["DROPBOX_APP_SECRET"])
          )
          res.raise_for_status()
          access_token = res.json()["access_token"]
          print("[✓] Nuevo access_token obtenido.")

          dbx = dropbox.Dropbox(access_token)

          folder = "data"
          today = datetime.today().strftime("%Y-%m-%d")
          base_dropbox_path = f"/Scraping-G5/{today}"

          for root, dirs, files in os.walk(folder):
              for name in files:
                  local_path = os.path.join(root, name)
                  relative_path = os.path.relpath(local_path, folder)
                  dropbox_path = f"{base_dropbox_path}/{relative_path.replace(os.sep, '/')}"

                  with open(local_path, "rb") as f:
                      dbx.files_upload(f.read(), dropbox_path, mode=dropbox.files.WriteMode.overwrite)
                      print(f"[✓] Subido: {dropbox_path}")
          EOF
