name: Scraping Diario Grupo 5

on:
  schedule:
    - cron: '0 3 * * *'  # 3 AM UTC = 10 PM hora Perú
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install requests beautifulsoup4 dropbox

      - name: Ejecutar scraper.py
        run: python scraper.py

      - name: Subir archivos a Dropbox
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        run: |
          python <<EOF
          import os
          import dropbox
          from datetime import datetime

          folder = "data"
          today = datetime.today().strftime("%Y-%m-%d")
          base_dropbox_path = f"/Scraping-G5/{today}"

          dbx = dropbox.Dropbox(os.environ["DROPBOX_TOKEN"])

          for root, dirs, files in os.walk(folder):
              for name in files:
                  local_path = os.path.join(root, name)
                  relative_path = os.path.relpath(local_path, folder)
                  dropbox_path = f"{base_dropbox_path}/{relative_path.replace(os.sep, '/')}"
                  with open(local_path, "rb") as f:
                      dbx.files_upload(f.read(), dropbox_path, mode=dropbox.files.WriteMode.overwrite)
                  print(f"Subido: {dropbox_path}")
          EOF

